### ISSUE TITLE
problems in "Search Similar Images" doc

### ISSUE THREAD

**Issue by mgogoulos** [jina-ai/jina#4277]
Hi, having installed jina through pip (v 2.6.4), I tried to follow https://docs.jina.ai/datatype/image/image2image/ but it fails

I guess this is deprecated?

```
from jina.types.document.generators import from_files
...
ModuleNotFoundError: No module named 'jina.types.document'
```

Nex, FlashImageEmbedder is not defined/imported before

```
.add(uses=FlashImageEmbedder, name="Encoder")
...
NameError: name 'FlashImageEmbedder' is not defined

```

Thanks

**Comment by mgogoulos** [comment]
Hi, kudos for the lightning-fast reply!

I now install all dependencies for this doc using

```
pip install jina==2.5 ipython vissl fairscale lightning-flash[image]
```

perform the small change (`FlashImageEmbedder` to `FlashImageEncoder`)

but now end up on a dependency chaos

```
        Encoder@69249[C]:can not load the executor from FlashImageEncoder
        Encoder@69249[E]:ExecutorFailToLoad() during <class 'jina.peapods.runtimes.zmq.zed.ZEDRuntime'> initialization
    self._embedder = ImageEmbedder(embedding_dim=1024)
TypeError: __init__() got an unexpected keyword argument 'embedding_dim'
```

The pip install command brought me

```
lightning-flash             0.6.0
pytorch-lightning           1.5.10
```

which is clearly not what it needs. 

Suggestions on what versions of flash to install? Even better would be to get the exact environment this needs to work!

Thanks

**Comment by JoanFM** [comment]
Hey @mgogoulos 

Sorry for the late reply, we have been working on releaing 3.0 and putting all these `tutorials` into the `Learning Portal` and should be soon available.

@alexcg1 @CatStark can you please point to the proper section?

**Comment by alexcg1** [comment]
@Shubhamsaboo is leading these efforts. He can answer better than me

**Comment by Shubhamsaboo** [comment]
Hey, @mgogoulos! 

Sorry for the trouble with the tutorial, we were in the process of migrating them from Jina 2 to Jina 3! 

You can find the working colab notebook for the same tutorial -> https://colab.research.google.com/github/jina-ai/tutorial-notebooks/blob/main/image2image.ipynb

Soon these changes with all other tutorials will be reflected on our [Learning Bootcamp](https://learn.jina.ai/). 

Hope this helps and thanks for being patient!

**Comment by mgogoulos** [comment]
I will give it a try, thanks a lot for replying here

**Comment by CatStark** [comment]
Hi @mgogoulos ,

No problem. I'll close the issue now but feel free to open a new one if we can help with anything else :)
