### ISSUE TITLE
module 'docarray' has no attribute '__version__' when upgrading jina from 2.6.4 to 2.6.5.dev60

### ISSUE THREAD

**Issue by mapleeit** [jina-ai/jina#4194]
**Describe the bug**

Reproduces steps:

### 1. create a new pyenv
`pyenv virtualenv test1`

### 2. use this new env
`pyenv activate test1`

### 3. check jina
`jina -v` -> no jina, good

### 4. install 2.6.4
`pip install jina==2.6.4`
`jina -v` -> 2.6.4, good

### 5. upgrade jina 
`pip install -U --pre jina`
`jina -v` -> **throw error, werid**

```
Traceback (most recent call last):
  File "/Users/miaozhaofeng/.pyenv/versions/test1/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/Users/miaozhaofeng/.pyenv/versions/3.9.5/envs/test1/lib/python3.9/site-packages/cli/__init__.py", line 107, in main
    from cli import api
  File "/Users/miaozhaofeng/.pyenv/versions/3.9.5/envs/test1/lib/python3.9/site-packages/cli/api.py", line 1, in <module>
    from jina.peapods.runtimes.head import HeadRuntime
  File "/Users/miaozhaofeng/.pyenv/versions/3.9.5/envs/test1/lib/python3.9/site-packages/jina/__init__.py", line 68, in <module>
    __docarray_version__ = _docarray.__version__
AttributeError: module 'docarray' has no attribute '__version__'
```

### 6. check docarray package

```
❯ ls /Users/miaozhaofeng/.pyenv/versions/3.9.5/envs/test1/lib/python3.9/site-packages/docarray
__pycache__ document    proto       score
array       math        resources   types.py
```

❌ **No `__init__.py`!** WHY

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by jacobowitz** [comment]
I understood what happens if you do the steps you described:

1. `docarray` gets installed into your site-packages in your venv as a new dependency
2. Jina 2.6.4 gets uninstalled which means removing the previous docarray folder. Unfortunately this docarray folder is also in your site-packages. Effectively this will destroy the new `docarray` installation.

I will try to come up with some workaround in Jina setup

**Comment by jacobowitz** [comment]
We decided that this cant be easily fixed. The recommend workaround is to not upgrade Jina, but rather install in a new venv oder uninstall the old jina version first.
